import { Typography } from '@mui/material'
import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Teacup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Typography component='h1' variant='h1'>
        Teacup
      </Typography>

     
    </div>
  )
}
